version: 2.1

jobs:
  Build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  Test:
    docker:
      - image: circleci/node:13.8.0
# it is better to use save cache to avoid installing the nmp packages in both test and biuld jobs
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  Analyze:
    docker:
    - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit
    
    
   
workflows:
  My_Work_Flow:
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Analyze:
          requires:
            - Test
